"""initialize database

Revision ID: 17b04c475173
Revises: 
Create Date: 2023-06-19 19:28:22.141712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b04c475173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzing_histories',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('unique_word_count', sa.Integer(), nullable=True),
    sa.Column('word_list', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyzing_histories')
    # ### end Alembic commands ###
